[project]
name = "uqEcoli"
version = "0.0.1"
description = "uqEcoli"
authors = [{ name = "Alex Patrie", email = "alexanderpatrie@gmail.com" }]
requires-python = ">=3.12.12"
readme = "README.md"
dependencies = [
    "plotly",
    "polars",
    "pydmd",
    "pytuq",
    "ray[data,train,tune]",
    "salib",
    "sobol",
    "typer",
    "uqpy",
    "vecoli",
    "vl-convert-python",
]

[project.scripts]
uq = "uq.cli:app"

[tool.hatch.build.targets.sdist]
include = [
    "uq",
    "apollo",
    "tests"
]

[tool.hatch.build.targets.wheel]
include = [
    "uq",
    "apollo",
    "tests"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
app = [
    "altair",
    "marimo[recommended]",
    "vegafusion>=2.0.3",
]
dev = [
    "deptry",
    "mypy",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "tox",
]
docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
]
music = [
    "music21",
    "partitura",
]

[tool.uv]
default-groups = [
    "app",
    "dev",
    "docs"
]

[tool.uv.sources]
vecoli = { path = "../vEcoli-private", editable = true }

[tool.mypy]
files = ["uq"]
strict = true
exclude = ['^tutorials/*', '^music/*']

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov-report=html"

[tool.deptry]
exclude = [".venv/*", "tutorials/*"]
ignore = ["DEP002", "DEP003", "DEP004", "DEP001"]

[tool.ruff]
target-version = "py39"
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # "DEP001",
    "A001",
    "A002",
    "B008",
    "B007",
    "B904",
    "C414",
    "C416",
    "C417",
    "C419",
    "E722",
    "RUF012",
    "S311",
    "TRY002",
    "TRY003",
    "TRY201",
    "TRY300",
    "UP006",
    "S603",
    "S324",
    "S301",
    "F401",
    "SIM108",
    "F841",
    "RUF002",
    "RUF001",
    "C901",
    "S608",
    "B028",
    "RUF005",
    "S112",
    "RUF022",
    "C401",
    "B018",
    "C408"
]
exclude = [".venv/*", "docs/*", "tutorials/*", "examples/*"]

[tool.ruff.format]
preview = true

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["uq"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]
