# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Set the OS, Python version, and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the "uq/docs/" directory with Sphinx
sphinx:
  configuration: uq/docs/conf.py
  builder: html
  fail_on_warning: false

# Install dependencies
python:
  install:
    - requirements: uq/docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - uq

# Optionally build localized versions
# localization:
#   - en
